"""Add article views

Revision ID: 0339c8491b87
Revises: 351905d23764
Create Date: 2017-10-16 17:40:03.930000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0339c8491b87'
down_revision = '351905d23764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('number_of_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'number_of_views')
    # ### end Alembic commands ###
