"""add last login date

Revision ID: 530001b0f99e
Revises: 
Create Date: 2017-10-11 00:27:48.438000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530001b0f99e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('register_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_date')
    op.drop_column('users', 'last_login_date')
    # ### end Alembic commands ###
